### ISSUE TITLE
Jest and Enzyme with NextJS

### ISSUE THREAD

**Issue by mheras** [Sebastp/Next-react-graphql-apollo_Boostrap#1]
Hi!! 

Congrats on your work!
I'm an experienced Java developer but a beginner with frontend development (JS + NextJS + React).
Could you please point me to a decent documentation on how to configure NextJS 9 with Jest and Enzyme?

Thanks in advance!

PS: I know that the issues section on Github is not the way to ask questions, but since you don't have any, I assume it wouldn't be any problem to you.

**Comment by Sebastp** [comment]
Thanks a lot, mheras

I haven't tried it yet myself so I don't know if you'll have any issues implementing it into next.js project but here are some great sources how you can test with enzyme and jest;
https://medium.com/codeclan/testing-react-with-jest-and-enzyme-20505fec4675
https://www.youtube.com/watch?v=XUlGzJLZe2Q
https://airbnb.io/enzyme/

I also like to see how others did it what I want to archive so I found two great Next boostraps that use enzyme and Jest. I'm sure by looking at their code you'll figure something out.
**https://github.com/atherosai/next-react-graphql-apollo-hooks
https://github.com/kriasoft/react-starter-kit**

If you have any other questions you can create another issue or just email me, will be happy to help :)
